# URLs and checksums for the plastimatch binary archives that this project wraps.
#
# This file is the seam between the two halves of the project: something builds
# per-platform plastimatch archives and attaches them to a GitHub release, and this file
# pins exactly which ones a wheel is built from. The wheel layer never knows or cares who
# produced them -- so when upstream plastimatch starts publishing its own binaries, only
# the three variables below change and nothing else in the repo moves.
#
# Regenerate the auto-generated section with:
#
#   python scripts/update_plastimatch_urls.py --repo <owner>/<repo> --tag <tag>
#
# Two cache variables allow repointing a build without editing this file:
#
#   -DPLASTIMATCH_BINARIES_BASE_URL=file:///path/to/dir   # archives from a local dir
#
# Note that the checksums are always enforced. To build against a different set of
# archives, run the update script rather than overriding the hash check.

# These two are rewritten by the update script along with the checksums below, and must stay
# consistent with them: they are what turns a pinned filename into a URL. The tag is an
# immutable binaries release, never a rolling pointer such as "latest" -- the checksums below
# describe the assets of one specific release, so a tag whose assets can be replaced would
# break every wheel build the moment it moved.
set(PLASTIMATCH_BINARIES_REPO "ImagingDataCommons/plastimatch-python-distributions"
  CACHE STRING "GitHub repository hosting the plastimatch binary archives")
set(PLASTIMATCH_BINARIES_TAG "binaries-1.10.0-1"
  CACHE STRING "Release tag hosting the plastimatch binary archives")
set(PLASTIMATCH_BINARIES_BASE_URL ""
  CACHE STRING "Override the base URL the archives are fetched from (default: the GitHub release)")

# The section below is auto-generated by scripts/update_plastimatch_urls.py
# Do not edit this section directly.

set(plastimatch_version "1.10.0")
set(plastimatch_commit  "db24480")

set(linux_filename        "plastimatch-1.10.0-linux-20260807-db24480.zip")
set(linux_sha256          "91b91ade88fd68ada63f84474ffb07edfaf7ad985603b4516ea457f9cc5e4443")

set(macos_arm64_filename  "plastimatch-1.10.0-mac-arm64-20260807-db24480.zip")
set(macos_arm64_sha256    "7fb52f2aa88a5e17df6111f17bf4a50463436c99afa2959d1943ce4dd68b12b9")

set(macos_x86_64_filename "plastimatch-1.10.0-mac-x86_64-20260807-db24480.zip")
set(macos_x86_64_sha256   "fa6f0c3b678db89c455578887bfd474c199e68ece634b4a935946d0f42c6d736")

set(win64_filename        "plastimatch-1.10.0-win64-20260807-db24480.zip")
set(win64_sha256          "4cb6e779de6a735defa5986576a4cd27ec4b21d5035a308090e3ad71a87e240e")

# The section above is auto-generated by scripts/update_plastimatch_urls.py
# Do not edit this section directly.

cmake_host_system_information(RESULT is_64bit QUERY IS_64BIT)

set(archive "linux")

if(APPLE)
  # Deliberately keyed off CMAKE_SYSTEM_PROCESSOR rather than CMAKE_OSX_ARCHITECTURES:
  # this project does not cross-compile. Each macOS wheel is built on a runner of its own
  # architecture (see .github/workflows/cd.yml), because the archive being wrapped is a
  # prebuilt single-architecture binary that cannot be retargeted at wheel-build time.
  if(CMAKE_SYSTEM_PROCESSOR STREQUAL "arm64")
    set(archive "macos_arm64")
  else()
    set(archive "macos_x86_64")
  endif()
endif()

if(WIN32)
  if(is_64bit AND NOT (${CMAKE_SYSTEM_PROCESSOR} STREQUAL "ARM64"))
    set(archive "win64")
  else()
    message(FATAL_ERROR
      "No plastimatch archive is published for this Windows architecture "
      "(CMAKE_SYSTEM_PROCESSOR=${CMAKE_SYSTEM_PROCESSOR}). Only 64-bit x86 is supported.")
  endif()
endif()

if(NOT DEFINED "${archive}_filename")
  message(FATAL_ERROR "Failed to determine which archive to download: '${archive}_filename' is not defined")
endif()

if(NOT DEFINED "${archive}_sha256")
  message(FATAL_ERROR "Could you make sure variable '${archive}_sha256' is defined ?")
endif()

set(plastimatch_archive_filename "${${archive}_filename}")
set(plastimatch_archive_sha256 "${${archive}_sha256}")

if(PLASTIMATCH_BINARIES_BASE_URL)
  set(_base_url "${PLASTIMATCH_BINARIES_BASE_URL}")
else()
  set(_base_url
    "https://github.com/${PLASTIMATCH_BINARIES_REPO}/releases/download/${PLASTIMATCH_BINARIES_TAG}")
endif()

set(plastimatch_archive_url "${_base_url}/${plastimatch_archive_filename}")
