#!/usr/bin/env python3
"""
Regenerate the auto-generated section of ``plastimatchUrls.cmake``.

Reads the assets attached to a GitHub release, downloads each platform archive, computes its
SHA256, and rewrites the pinned filenames and checksums in place. Run this whenever the
wheels should be built from a new set of binaries:

    python scripts/update_plastimatch_urls.py \
        --repo ImagingDataCommons/plastimatch-python-distributions --tag binaries-1.10.0-1

``--repo``/``--tag`` name the release hosting the archives, normally a binaries-* release of
this repository cut by build-binaries.yml. Both are written into plastimatchUrls.cmake next to
the checksums, so the file always records where the bytes it pins came from.

Set ``GITHUB_TOKEN`` in the environment to read a private repository or to avoid the
unauthenticated API rate limit.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
from pathlib import Path
from urllib.request import Request, urlopen

# Maps the CMake variable prefix to the substring identifying that platform's asset. The
# archive names are produced by the platform build workflows and look like
# plastimatch-1.10.0-mac-arm64-20260804-8e65f51.zip
PLATFORM_PATTERNS = {
    "linux": "-linux-",
    "macos_arm64": "-mac-arm64-",
    "macos_x86_64": "-mac-x86_64-",
    "win64": "-win64-",
}

VERSION_RE = re.compile(r"^plastimatch-([0-9][0-9.]*)-")
COMMIT_RE = re.compile(r"-([0-9a-f]{7,40})\.(?:zip|tar\.gz)$")

BLOCK_RE = re.compile(
    r"# The section below is auto-generated by scripts/update_plastimatch_urls\.py\n"
    r"# Do not edit this section directly\.\n"
    r"[\s\S]+?"
    r"# The section above is auto-generated by scripts/update_plastimatch_urls\.py\n"
    r"# Do not edit this section directly\.\n"
)

# PLASTIMATCH_BINARIES_REPO and _TAG live outside the auto-generated block, but they are half
# of the pin: the block names files and checksums, and these two turn a filename into a URL.
# Rewriting only the block leaves the file self-consistent-looking and completely broken --
# new filenames fetched from the previous release, every one a 404. So they are rewritten too.
REPO_RE = re.compile(r'(?m)^(set\(PLASTIMATCH_BINARIES_REPO ")[^"]*(")')
TAG_RE = re.compile(r'(?m)^(set\(PLASTIMATCH_BINARIES_TAG ")[^"]*(")')

CHUNK = 1 << 20


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--repo", required=True, help="owner/name of the GitHub repository"
    )
    parser.add_argument("--tag", required=True, help="release tag hosting the archives")
    parser.add_argument(
        "--cmake-file",
        type=Path,
        default=Path(__file__).parents[1] / "plastimatchUrls.cmake",
        help="path to plastimatchUrls.cmake",
    )
    return parser.parse_args()


def _request(url: str, accept: str) -> Request:
    headers = {"Accept": accept, "User-Agent": "update_plastimatch_urls"}
    token = os.environ.get("GITHUB_TOKEN")
    if token:
        headers["Authorization"] = f"Bearer {token}"
    return Request(url, headers=headers)


def fetch_release(repo: str, tag: str) -> dict:
    url = f"https://api.github.com/repos/{repo}/releases/tags/{tag}"
    with urlopen(_request(url, "application/vnd.github+json")) as response:
        return json.load(response)


def sha256_of(asset: dict) -> str:
    """Stream the asset and return its SHA256, without holding it all in memory."""
    digest = hashlib.sha256()
    request = _request(asset["url"], "application/octet-stream")
    with urlopen(request) as response:
        while chunk := response.read(CHUNK):
            digest.update(chunk)
    return digest.hexdigest()


def generate_block(assets: list[dict]) -> str:
    selected: dict[str, dict] = {}
    for key, pattern in PLATFORM_PATTERNS.items():
        matches = [a for a in assets if pattern in a["name"]]
        if not matches:
            msg = (
                f"No asset matching '{pattern}' found in the release. "
                f"Available: {sorted(a['name'] for a in assets)}"
            )
            raise ValueError(msg)
        if len(matches) > 1:
            msg = f"Multiple assets match '{pattern}': {[a['name'] for a in matches]}"
            raise ValueError(msg)
        selected[key] = matches[0]

    first = next(iter(selected.values()))["name"]
    version_match = VERSION_RE.search(first)
    if version_match is None:
        msg = f"Cannot determine plastimatch version from asset name '{first}'"
        raise ValueError(msg)
    version = version_match.group(1)

    commit_match = COMMIT_RE.search(first)
    commit = commit_match.group(1) if commit_match else "unknown"

    lines = [
        "# The section below is auto-generated by scripts/update_plastimatch_urls.py",
        "# Do not edit this section directly.",
        "",
        f'set(plastimatch_version "{version}")',
        f'set(plastimatch_commit  "{commit}")',
        "",
    ]

    for key, asset in selected.items():
        checksum = sha256_of(asset)
        print(f"{checksum}  {asset['name']}")
        lines.append(f"set({key}_filename".ljust(26) + f'"{asset["name"]}")')
        lines.append(f"set({key}_sha256".ljust(26) + f'"{checksum}")')
        lines.append("")

    lines += [
        "# The section above is auto-generated by scripts/update_plastimatch_urls.py",
        "# Do not edit this section directly.",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    args = parse_args()

    release = fetch_release(args.repo, args.tag)
    assets = release.get("assets", [])
    if not assets:
        msg = f"Release '{args.tag}' in {args.repo} has no assets"
        raise ValueError(msg)

    block = generate_block(assets)

    text = args.cmake_file.read_text(encoding="utf-8")
    if not BLOCK_RE.search(text):
        msg = f"Could not find the auto-generated block in {args.cmake_file}"
        raise ValueError(msg)

    text = BLOCK_RE.sub(block, text)

    for name, pattern, value in (
        ("PLASTIMATCH_BINARIES_REPO", REPO_RE, args.repo),
        ("PLASTIMATCH_BINARIES_TAG", TAG_RE, args.tag),
    ):
        text, count = pattern.subn(lambda m, v=value: m.group(1) + v + m.group(2), text)
        if count != 1:
            msg = (
                f"Expected exactly one {name} assignment in {args.cmake_file}, found {count}. "
                f"The checksums would then point at assets fetched from a different release."
            )
            raise ValueError(msg)

    args.cmake_file.write_text(text, encoding="utf-8")
    print(f"Updated {args.cmake_file} from {args.repo}@{args.tag}")


if __name__ == "__main__":
    main()
